version: '2'

services:
  app:
    image: 'clisthenes:latest'
    build:
      context: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-clisthenes:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DISCORD_TOKEN=

  db-clisthenes:
    image: 'postgres:alpine'
    container_name: db-clisthenes
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"