spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/compose-postgres
#    username: compose-postgres
#    password: compose-postgres
